var answer= [
	['enzymes'],
	['digestion'],
	['amoeba'],
	['anal pore'],
	['extracellular'],
	['cilia'],
	['fluid feeders','feeders of fluid'],
	//-9
	['duodenum','jejunum','lleum'],
	['duodenum','jejunum','lleum'],
	['duodenum','jejunum','lleum'],
	//-10
	['amoeboid cells'],
	['compound eye','eye'],
	['antenna'],
	['maxillary palp'],
	['labium'],
	['dentition'], //-15
	//-16
	/*
	['herbivore'],
	['cropping'],
	['grinding'],
	*/
	//tar
	['Herbivore','it is a Herbivore','its a Herbivore','a Herbivore'],
	[''],
	[''],
	[''],
	
	['Gall bladder'],
	['Large Intestine (colon)','Large Intestine','colon'],
	['Alkaline'],
	//-20 -T.A required
	[''],
	[''],
	
	['Oesophagus'], 
	['Crop'],
	['Gizzard'],
	['Pancreas'],
	['Duodenum','Duodenum (small intestine)','small intestine'],
	['Crushing of food','for Crushing food','for Crushing of food','food Crushing','Crushes food'],
	[''],
	[''],
	[''],
	[''],
	[''],
	['It is crushed','crushed','It get crushed'],
	['Crop'],
	['Gizzard'],
	['Intestine'],
	['Anus'],
	['Mouth'],
	['Fine branches of small intestine','Fine branches'],
	['Herbivore','A sheep','sheep'],
	['Carnivore','A dog','dog'],
	['Diastema'],
	['Hard pad'],
	['Incissors'],
	['Incisor'],
	['Canine'],
	['Canacial Teeth'],
	['Grasshopper'],
	['Housefly'],
	['Cockroach'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
	//[''],
	//['',''],
	 
];