var answer= [
	['Aquatic Habitat','Terrestial Habitat','Aboriel Habitat'],
	['Aquatic Habitat','Terrestial Habitat','Aboriel Habitat'],
	['Aquatic Habitat','Terrestial Habitat','Aboriel Habitat'],
	['Tertiary Consumer'],
	['Producer'],
	['An ecosystem','ecosystem','ecological system','ecological systems'],
	['Producer'],
	['niche'],
	['The sun','sun'],
	['Ecosystem'],
	['Biomass'],
	['Pyramid of energy'],
	['Mineral Salts'],
	['Toad, 3rd Trophic Level','Toad 3rd Trophic Level','Toad, third Trophic Level','Toad Third Trophic Level','Toad belongs to Third Trophic Level'],
	['Producer (Aquatic habitat)','Producer','Aquatic Producer'],
	['food web'],
	['Ecological pyramid (Pyramid of number)','Ecological pyramid','pyramid of Ecological','Pyramid of number'],
	['Thermodynamics'],
	['Pyramid of energy'],
	['Gross primary productivity'],
	['Net primary productivity'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
];