var answer= [
	['Robert Hook'],
	['lipids','protein'],
	['lipids','protein'],
	['Nucleus'],
	['Unicellular','accelular'],
	['multicellular'],
	['nuclear membrance'],
	['plasma membrane'],
	['cellulose'],
	['Robert Hook','mattias schlieden','theodor schwann','dujardin'],
	['Robert Hook','mattias schlieden','theodor schwann','dujardin'],
	['Robert Hook','mattias schlieden','theodor schwann','dujardin'],
	//9
	['mitochondrion'],
	['gene'],
	['nucleolus'],
	['as an independent organism','independent organism','organism'],
	//3
	['amoeba'],
	['Sperm cell'],
	['Chloroplast'],
	['Deoxoribonucleic Acid (DNA)','Deoxoribonucleic Acid. (DNA)','Deoxoribonucleic Acid','DNA'],
	['Nitrogen','Phosphorus','Oxygen','Carbon'],
	['Nitrogen','Phosphorus','Oxygen','Carbon'],
	['Nitrogen','Phosphorus','Oxygen','Carbon'],
	['Nitrogen','Phosphorus','Oxygen','Carbon'],
	['Chlamydomonas'],
	['Volvox'],
	['Unicellular','acellular','a cellular','They have only one cell','one cell'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
];