var answer= [
	['diffusion'],
	['diffusion'],
	['concentration gradient','gradient of concentration'],
	['Osmosis'],
	['Yam Tissue'],
	['Sugar Solution'],
	['Endosmosis'],
	['semipermeable membrane','permeable membrane','selectively permeable membrane'],
	['Isotonic Solution'],
	['Hypotonic'],
	['Active Transport'],
	['Plasma Membrane'],
	['Osmosis'],
	['Plasmolysis'],
	['Diffusion'],
	['Osmosis'],
	['plasmolysis'],
	//6
	/*['Diffusion'],
	['gaseous'],
	*/
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
];