var answer= [
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Water','Protein','Nucleic','Acids','Carbohydrates','Minerals','Lipids','Vitamins','Nucleic Acids'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	['Carbon','Hydrogen','Nitrogen','Oxygen','Sulphur','Phosporus'],
	
	['Carbohydrate','Protein','Lipids','fats and oil','fat an oil'],
	['Carbohydrate','Protein','Lipids','fats and oil','fat an oil'],
	['Carbohydrate','Protein','Lipids','fats and oil','fat an oil'],
	['Magnesium','iron'],
	['Adenosine Triphosphate'],
	['Mitochondria'],
	['Cytoplasm'],
	['Pyruvic Acid'],
	//10
	['38','Thirty eight'],
	['Lactic Acid'],
	['Mitosis'],
	['46','forty six'],
	['Telophase'],
	['Nastic Movement'],
	['Phototropism'],
	['Clones'],
	['Sexual Reproduction'],
	['Replication'],
	['Pseudopod','Pseudopoda'],
	['Cilia'],
	['Flagellum'],
	['Flagella'],
	['Flagelum'],
	//(i)
	['Vegetative Propagation'],
	//1a
	['Conjugation'],
	['4','four'],
	//2c
	['B'],
	['B'],
	[''],
	['Prophase'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
];