var answer= [
	['Carbohydrate','Protein deposits','Mineral Salts'],
	['Carbohydrate','Protein deposits','Mineral Salts'],
	['Carbohydrate','Protein deposits','Mineral Salts'],
	['Hydrostatic Skeleton'],
	['Endoskeleton'],
	['Calcium Phosphate','Calcium Carbonate'],
	['Calcium Phosphate','Calcium Carbonate'],
	['Hyaline Cartilage','Cartilage of Hyaline'],
	['Ossification'],
	['Vertebraterial Canal'],
	['16','sixteen'],
	['neck'],
	['12','Twelve'],
	['ligaments'],
	['tendons'],
	['Floating Ribs'],
	['Acetabulum'],
	//16
	['Pectoral girdle','Pectoral'],
	['Illum'],
	['Pubic'],
	['Ischium'],
	['Synovial fluid'],
	['ball and socket'],
	['voluntary'],
	['skull'],
	['immovable'],
	['Zylem'],
	//23
	['the turgid perenchyma','turgid perenchyma'],
	['Tracheids','Vessels','Fibre','Parenchyma'],
	['Tracheids','Vessels','Fibre','Parenchyma'],
	['Tracheids','Vessels','Fibre','Parenchyma'],
	['Tracheids','Vessels','Fibre','Parenchyma'],
	//24
	['Cambium'],
	['secondary Zylem','wood'],
	['Immovable Joint'],
	//a 
	['Femur'],
	['Radius'],
	['Ulna'],
	['Scapula'],
	['Sacrum'],
	['Cervical Vertebra'],
	['Cervical Vertebra'],
	['Cervical Vertebra','Cervical Vertebra (Lateral View)'],
	['Pectoral Girdle'],
	['Lumber Vertebra'],
	['Thoracic Vertebra'],
	['Pelvic Girdle'],
	//8
	['Lower Fore Limb'],
	['Lower Hind Limb'],
	['Upper hind Limb (Femur)','Upper hind Limb','Femur'],
	['Upper fore Limb (Humerus)','Upper fore Limb','Humerus'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
];