var answer= [
	['Upper Epidermis'],
	['Chloroplast'],
	['Lower Epidermis'],
	['Intercellular air space'],
	['Experimental Plant'],
	['Bent glass tubing'],
	['Two hole stopper'],
	['Culture Solution'],
	['Gas jar'],
	[''],
	// starting from 5
	['Oxygen','Glucose'],
	['Oxygen','Glucose'],
	['Photolysis of Water','Water Photolysis'],
	['Chlorophyl'],
	[''],
	['Variegated'],
	['Etiolated'],
	['Nitrogen Fixation','Fixation of Nitrogen'],
	['Nitrobacter'],
	['Chlorophyl'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
];