var answer= [
	['Heterotropic mode','Holozoic'],
	['Carbohydrate','Fats and Oil','Protein'],
	['Carbohydrate','Fats and Oil','Protein'],
	['Carbohydrate','Fats and Oil','Protein'],
	['essential amino acids'],
	['Eight','8'],
	['Chemosynthetic','Autotrophic'],
	['Symbiotic'],
	['A Pink Colour','Pink','Colour Pink'],
	['Symbiosis','Mutualism'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
];