var answer= [
	['Tissue Fluid ','blood','lymph'],
	['Tissue','blood','lymph','Tissue Fluid '],
	['Tissue','blood','lymph','Tissue Fluid '],
	['37','thirty seven'],
	['7.4'],
	['negative feedback'],
	['brain'],
	
	['hypothalamus'],
	['anti-diuretic'],
	['glomerullar nephrites'],
	['diuretics'],
	['dialysis','kidney transplant'],
	[''],
	['urea'],
	['glucose'],
	['entamoeba histolytica'],
	
	['malphighian layer'],
	['sweat gland'],
	['Sebaceous gland'],
	['Hair erector muscle'],
	['Hair root'],
	['Abscisic Acid'],
	['Adrenaline','Noradrenaline'],
	['Adrenaline','Noradrenaline'],
	['Oestrogen','Progesterone'],
	['Oestrogen','Progesterone'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['The glomerulus','glomerulus'],
	['Antidiuretic hormone'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
	 
]