var answer= [
	['nervous system','endocrine system','nervous','endocrine'],
	['nervous system','endocrine system'],
	['nerve impulses','nerve impulse'],
	['central'],
	['Meninges'],
	['Hypothalamus'],
	['left'],
	['Spinal cord'],
	['Cerebral cortex'],
	['Cerebro spinal'],//9
	['Medulla Oblongata'],
	['The Thalamus','Thalamus'],
	['dendrite'],
	['axon'],
	['myelin sheath'],
	// remove 12, 15, 20
	['dendrite'],
	['nodes of ranvier'],
	['cytoplasm'],
	['nucleus'],
	['schwann','schwann cells'],
	[''],
	[''],
	[''],
	['sympathetic nervous system','sympathetic nervous'],
	['central'],
	['Grey matter'],
	['White matter'],
	['Spinal nerve'],
	['Effector neuron'],
	['synapse'],
	[''],
	[''],
	[''],
	['Cerebral hemisphere'],
	['Medulla Oblongata'],
	['Cerebellar hemisphere'],
	['Olfactory lobes'],
	['Cerebral hemisphere'],
	['Cerebellar hemispehere'],
	['Medulla oblongata'],
	['Spinal Cord'],
	[''],
	['Medulla Oblongata','iv','iv Medulla Oblongata'],
	['Hypothalamus'],
	[''],
	[''],
	[''],
	[''],
	['']
	//[''],
	//['',''],
	 
];