var answer= [
	['photo'],
	['touch','pressure','pain','temperature'],
	['touch','pressure','pain','temperature'],
	['touch','pressure','pain','temperature'],
	['touch','pressure','pain','temperature'],
	['tongue'],
	['pacinian'],
	['pain'],
	['cold'],
	// emove 15 20 14 16 17 19
	['heat'],
	['touch'],
	['pressure'],
	['Olfactory'],
	['Taste','Smell'],
	['Taste','Smell'],
	['Cornea','Aqueous Humour','Lens','Vitreous Humour'],
	['Cornea','Aqueous Humour','Lens','Vitreous Humour'],
	['Cornea','Aqueous Humour','Lens','Vitreous Humour'],
	['Cornea','Aqueous Humour','Lens','Vitreous Humour'],
	['Rods cells'],
	['eye\’s power of accomodation','eye power of accomodation','accomodation'],
	[''],
	[''],
	['using a diverging lens','diverging lens','the uses of diverging lens are all correct','diverging lens'],
	['Night blindness','Xerophthalmia'],
	['Night blindness','Xerophthalmia'],
	[''],
	[''],
	['Tympanic'],
	['Hammer','Malleus'],
	['Anvil','Incus'],
	['Stirrup','Stapes'],
	['Oval window'],
	['Cochlea fluid'],
	['Cornea','pupil','lens'],
	['Cornea','pupil','lens'],
	['Cornea','pupil','lens'],
	['Optic nerve'],
	['No'],
	['No'],
	['Central nervous system','Central'],
	[''],
	[''],
	['c'],
	['b and d','b,d','bd','b d'],
	['a'],
	[''],
	[''],
	[''],
	[''],
	[''],
	
	['the ear','ear','an ear'],
	['Semicircular canal','Semi circular canal'], 
	['Ampullae'],
	['Saccules'],
	['utricles'],
	[''],
	[''],
	['']
];