var answer= [
['Sex cells','gamates','Sex cell','gamate'],
['Zygote'],
['Diploid'],
['Four','4'],
['Haploid'],
['Hermaphrodite'],
[''],
[''],
['Aquatic'],
['Amniote'],//
['Air Space'],
['Yolk'],
['Albumen'],
['Chalaza'],
['Amniotic Fluid'],
['Shell Membrane'],
['Birds','Aves','Mammals'],
['Birds','Aves','Mammals'],
['Testes'],
['Epididymis'],
['Vasdeferens'],
['Oestrogen'],
['Corpus Luteum'],
['Progesterone hormone'],
['fallopian Tube','oviduct'],
['Superior Ovary'],
['Half inferior Ovary'],
['Inferior Ovary'],
['Wind pollinated flower','Anemophilous flower is a Wind pollinated flower','','Anemophilous flower is a flower that pollinated by Wind','Anemophilous flower is a flower that pollinated the Wind'], 
['Monoecious'],
['Dioecious'],
[''],
['Self pollination'],
['Wind','Insects'],
['Wind','Insects'],
['28days','','28 days','twenty eight days'],
['Testes'],
['Yes'],
['Ovary'],
['Oviduct'],
['22 days','twenty two','22days'],
['Placentation'],
['Marginal Placentation'],
['A sperm cell'],
['testes'],
['testosterone'],
['Nucleus'],
['Mitochondria'],
['Flagellum'],
['Bilateral symmetry'],
['Bisexual'],
['Marginal placentation'],
[''],
[''],
[''],
['']
	 
];