var answer= [ // 19
['embryo'],
['complete metamorphosis'],
['egg pod'], //geasshopper 
['nymph'],
['Wriggler'],
['Caterpillar'],
['Maggot'],
['Grub'],
['Grub'],
['Thyroxine'],
['External gill stage'],
['External Gill Stage'],
['Development of Hind Limb','Hind Limb'],
['Internal gill stage'],
['Nine','9'],
['Head'],
['Silken girdle'],
['Spiracle'],
['Abdomen'],
['Silken pad'],
['once in her lifetime','one time in her lifetime','once','one time','onetime'],
[''],
[''],
[''],
[''],
[''],
[''],
[''],//
['Air space'],// edit the image
['Amniotic Fluid'],
['Embryo'],
['Placenta'],
['Oxytocin','Oestrogen'],
['Oxytocin','Oestrogen'],
['Seed'],
['Fruit'],
['Growth Hormone'],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
['']
	 
];