var answer= [
['Mutations','spontanous change in genes','chromosomes'],
['red blood cells'],
['o'],
['Agglutinatination'],
['Size'],
['Tongue rolling'],
['Colour'],
['Ear lobes'],
['Ability to taste P.T.C','Ability to taste P.T.C','Ability to taste PTC (phenylthiocarbamide)'],
['DNA Fingerprints','DNA','Fingerprints'],
['AB'],
['direct'],
['survival'],
['intraspecific'],
['interspecific'],
['Colour change'],
['caste'],
['Queen','King','Workers','Soldiers'],
['Queen','King','Workers','Soldiers'],
['Queen','King','Workers','Soldiers'],
['Queen','King','Workers','Soldiers'],
['Touch','Smell','Visual Movements','Dances','body movement'],
['Touch','Smell','Visual Movements','Dances','body movement'],
['Touch','Smell','Visual Movements','Dances','body movement'],
['Mutation'],
['Mutagens'],
['Radiation'],
['Wolf packs'],
['HbaHbs'],
['Group O','o'],
['No'],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
['']
	 
];