var answer= [
['The law of independent assortment','The law of independent assortment of genes','law of independent assortment of genes'],
['its genotype','genotype'],
['Homozygous'],
['Phenotype'],
['Diploid'],
['Anaphase'],
['Chromosome Theory'],
['Replication'],
['3 : 1','3:1','3 to 1','three to one'],
['Loci '],
['Dihybrid'],
['hybrid'],
['Incomplete dominance'],
['Male'],
['Autosomes'],
['Sex linked character','trait'],
['Monosomic'],
['Rhesus Positive'],
['Rr'],
['Females'],
['Males'],
['3','three'],
['7','seven'],
[''],// leave empty
['Deoxyribonucleic Acid','DNA','Deoxyribonucleic Acid (DNA)'],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
[''],
['']
	 
];