var answer= [
	['diffusion'],
	['fluid','blood'],
	['open'],
	['streaming movement'],
	['air tubes','network of air tubes','a network of air tubes'],
	['pulmonary'],
	['plasma'],
	['bone marrow'],
	['haemoglobin'],
	['white blood cell'],
	['platelets'],
	['calcium'],
	['pericardium membrane'],
	['coronary artery'],
	['bicuspid'],
	['systole'],
	['hepatic artery','hepatic portal vein'],
	['hepatic portal vein','hepatic artery'],
	
	['pulmonary artery'],
	['sieve tubes','companion cells'],
	['sieve tubes','companion cells'],
	['osmosis','active transport'],
	['osmosis','active transport'],
	['Left Ventriole'],
	['Left Part'],
	['Phloem tissue','zylem tissue','Phloem','zylem'],
	['zylem tissue','Phloem tissue','Phloem','zylem'],
	/*
	['Bell Jar'],
	['Anhidrous Calcium Chloride'],
	['Hepatic portal vein'],
	['The right side','right side'],
	['Coronary artery'],
	['Left article'],*/
	['secchi disc'],
	[''],
	[''],
	[''],
	[''],
	['']
];