var answer= [
	['Respiration'],
	['Catabolic'],
	['circulatory'],
	['Body surfaces'],
	['tracheae'],
	['Gill filament'],
	['Alveoli'],
	['pleural membrane'],
	['lungs','moist skin'],
	['lungs','moist skin'],
	
	['Windpipe','trachea'],
	['Right bronchus'],
	['Outer pleural membrane','Outer pleural membrane'],
	['Left bronchus'],//-15
	['Bronchiole'],
	['Nose (Nasal opening)','Nasal opening','Nose'],
	['Diaphragm'],
	['Bronchi'],//-20
	['Stomata'],
	['Guard cells'],
	['Lenticels'],
	['Guard cells'],
	['Stomatal pore','Stomatal'],
	[''],
	[''],
	[''],
	[''],
	['Moist body surface'],
	['Gills'],
	['Gills'],
	['Lungs','alveoli'],
	['Lungs','alveoli'],
	['Plasma membrane'],
	['Moist skin'],
	['Tracheae'],
	['Bronchiole'],
	['Venule'],
	['Arteriole'],
	['Network of capillaries'],
	['Trachae'],
	['Addomonal airsac'],
	['Abdomenal Spiracles'],
	['Gill'],
	['Gill filament'],
	['Gill rakers'],
	['Gill arch'],
	[''],
	['Gill filament'],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	[''],
	['']
	 
];