var answer= [
	['Ammonia'],
	['Osmoregulatory'],
	[''],
	[''],
	['Nephridium'],
	['Green Gland'],
	['Malpighian Tubule'],
	['Uric acid'],
	['Renal artery'],
	['Oxygenated blood','its Oxygenated blood','it is Oxygenated blood'],
	['Glomerulus'],
	['Urinary Tubules'],
	[''],
	['Bowman’s capsule'],
	['Kidney','Liver','Lung'],
	['Kidney','Liver','Lung'],
	['Kidney','Liver','Lung'],
	['Active transport'],
	['Stomata','Lenticels','Intercellular air spaces'],
	['Stomata','Lenticels','Intercellular air spaces'],
	['Stomata','Lenticels','Intercellular air spaces'],
	['Water','Carbondioxide','Oxygen'],
	['Water','Carbondioxide','Oxygen'],
	['Water','Carbondioxide','Oxygen'],
	['Transpiration'],
	['Active Transport','Varying permeability of tubule','Hormonal control'],
	['Active Transport','Varying permeability of tubule','Hormonal control'],
	['Active Transport','Varying permeability of tubule','Hormonal control'],
	['Glomerulus','Proximal tubule and Henle’s lump','Distal tubule','At the bladder','in the bladder'],
	['Glomerulus','Proximal tubule and Henle’s lump','Distal tubule','At the bladder','in the bladder'],
	['Glomerulus','Proximal tubule and Henle’s lump','Distal tubule','At the bladder','in the bladder'],
	['Glomerulus','Proximal tubule and Henle’s lump','Distal tubule','At the bladder','in the bladder'],
	// - live 7 space for tar
	['urea'],
	['Renal Artery'],
	['Nephron'],
	['Liver'],
	['Flame Cell'],
	['Nucleus'], 
	['Lumen'],
	['Flagella'],
	['Tubule'],
	['Planaria'],
	[''],
	[''],
	['']
	 
];